[project]
name = "card-to-price"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "baml-cli>=0.1.0",
    "baml-py>=0.213.0",
    "dotenv>=0.9.9",
    "requests>=2.32.5",
    "yugioh>=0.0.26",
]
